window.DG_TRANSLATION_ROWS=[
['WELCOME TO','BIENVENUE À','ยินดีต้อนรับสู่','ДОБРО ПОЖАЛОВАТЬ В'],
['We are delighted to welcome you. We created this guide to help make your stay as enjoyable and comfortable as possible.','Nous sommes ravis de vous accueillir. Nous avons créé ce guide pour rendre votre séjour aussi agréable et confortable que possible.','เรายินดีเป็นอย่างยิ่งที่ได้ต้อนรับคุณ คู่มือนี้จัดทำขึ้นเพื่อให้การเข้าพักของคุณสะดวกสบายและเพลิดเพลินที่สุด','Мы рады приветствовать вас. Этот путеводитель создан, чтобы сделать ваше пребывание максимально приятным и комфортным.'],
['Villa address','Adresse de la villa','ที่อยู่วิลล่า','Адрес виллы'],['Scan location','Scanner la localisation','สแกนตำแหน่ง','Сканировать адрес'],['View on maps','Voir sur la carte','ดูบนแผนที่','Открыть карту'],
['Check-in & check-out','Arrivée et départ','เช็กอินและเช็กเอาต์','Заезд и выезд'],['Check-in','Arrivée','เช็กอิน','Заезд'],['Check-out','Départ','เช็กเอาต์','Выезд'],['From','À partir de','ตั้งแต่','С'],['Before','Avant','ก่อน','До'],
['Wi-Fi codes','Codes Wi-Fi','รหัส Wi‑Fi','Данные Wi‑Fi'],['Network','Réseau','เครือข่าย','Сеть'],['Password','Mot de passe','รหัสผ่าน','Пароль'],['Scan to connect','Scanner pour se connecter','สแกนเพื่อเชื่อมต่อ','Сканировать для подключения'],
['Rawai weather','Météo à Rawai','สภาพอากาศราไวย์','Погода в Раваи'],['Loading weather…','Chargement de la météo…','กำลังโหลดสภาพอากาศ…','Загрузка погоды…'],['Feels','Ressenti','รู้สึกเหมือน','Ощущается'],['Low / High','Min. / Max.','ต่ำ / สูง','Мин. / Макс.'],['Humidity','Humidité','ความชื้น','Влажность'],['Wind','Vent','ลม','Ветер'],['Refresh Rawai weather','Actualiser la météo de Rawai','อัปเดตสภาพอากาศราไวย์','Обновить погоду в Раваи'],
['Places of interest','Lieux d’intérêt','สถานที่น่าสนใจ','Интересные места'],['Sea Market','Marché aux poissons','ตลาดอาหารทะเล','Рыбный рынок'],
['Dream Garden Pool Villa','Villa Dream Garden avec piscine','ดรีมการ์เด้นพูลวิลล่า','Dream Garden — вилла с бассейном'],['Galerie photos','Galerie photos','แกลเลอรีรูปภาพ','Фотогалерея'],['Voir toutes les photos (20)','Voir toutes les photos (20)','ดูรูปภาพทั้งหมด (20)','Посмотреть все фото (20)'],['Tout','Tout','ทั้งหมด','Все'],['Extérieur','Extérieur','ภายนอก','Экстерьер'],['Piscine','Piscine','สระว่ายน้ำ','Бассейн'],['Salon','Salon','ห้องนั่งเล่น','Гостиная'],['Cuisine','Cuisine','ห้องครัว','Кухня'],['Chambres','Chambres','ห้องนอน','Спальни'],['Salles de bains','Salles de bains','ห้องน้ำ','Ванные комнаты'],['Terrasse','Terrasse','ระเบียง','Терраса'],['Jardin','Jardin','สวน','Сад'],['Aucune photo dans cette catégorie pour le moment.','Aucune photo dans cette catégorie pour le moment.','ขณะนี้ยังไม่มีรูปภาพในหมวดหมู่นี้','В этой категории пока нет фотографий.'],
['Information about the villa','Informations sur la villa','ข้อมูลเกี่ยวกับวิลล่า','Информация о вилле'],['3 bedrooms','3 chambres','3 ห้องนอน','3 спальни'],['3 bathrooms','3 salles de bains','3 ห้องน้ำ','3 ванные комнаты'],['Private pool — 12 × 5 m','Piscine privée — 12 × 5 m','สระว่ายน้ำส่วนตัว — 12 × 5 ม.','Частный бассейн — 12 × 5 м'],['Maximum occupancy: 6 guests','Capacité maximale : 6 personnes','ผู้เข้าพักสูงสุด 6 คน','Максимальная вместимость: 6 гостей'],['Living room and fully equipped kitchen','Salon et cuisine entièrement équipée','ห้องนั่งเล่นและครัวพร้อมอุปกรณ์ครบครัน','Гостиная и полностью оборудованная кухня'],['Covered parking for 2 cars','Parking couvert pour 2 voitures','ที่จอดรถในร่มสำหรับ 2 คัน','Крытая парковка на 2 автомобиля'],['800 m² land · 250 m² villa','Terrain de 800 m² · Villa de 250 m²','ที่ดิน 800 ตร.ม. · วิลล่า 250 ตร.ม.','Участок 800 м² · Вилла 250 м²'],
['Included','Inclus','รวมแล้ว','Включено'],['High-speed fiber Wi-Fi','Wi-Fi fibre haut débit','Wi‑Fi ไฟเบอร์ความเร็วสูง','Высокоскоростной оптоволоконный Wi‑Fi'],['25L Water Dispenser','Fontaine à eau de 25 L','เครื่องจ่ายน้ำดื่ม 25 ลิตร','Диспенсер для воды 25 л'],['Water','Eau','น้ำประปา','Вода'],['Laundry machine','Machine à laver','เครื่องซักผ้า','Стиральная машина'],['Barbecue gas','Gaz pour barbecue','แก๊สบาร์บีคิว','Газ для барбекю'],['Hair dryer','Sèche-cheveux','ไดร์เป่าผม','Фен'],['Pool towels','Serviettes de piscine','ผ้าเช็ดตัวสำหรับสระ','Полотенца для бассейна'],['Equipped kitchen','Cuisine équipée','ครัวพร้อมอุปกรณ์','Оборудованная кухня'],['Smart home system','Système domotique','ระบบสมาร์ทโฮม','Система умного дома'],['Indoor & outdoor speakers','Enceintes intérieures et extérieures','ลำโพงภายในและภายนอก','Колонки внутри и снаружи'],['100% LED lighting','Éclairage 100 % LED','ไฟ LED 100%','Освещение 100% LED'],['65" flat-screen TV & Box TV','Téléviseur écran plat 65" et Box TV','ทีวีจอแบน 65 นิ้ว และกล่องทีวี','Телевизор 65″ и ТВ-приставка'],['Dishwasher','Lave-vaisselle','เครื่องล้างจาน','Посудомоечная машина'],['Garden maintenance','Entretien du jardin','ดูแลสวน','Уход за садом'],
['Housekeeping','Entretien','บริการดูแลบ้าน','Уборка'],['Villa cleaning, bedsheets and towels changed once a week.','Nettoyage de la villa, draps et serviettes changés une fois par semaine.','ทำความสะอาดวิลล่าและเปลี่ยนผ้าปูที่นอนกับผ้าเช็ดตัวสัปดาห์ละครั้ง','Уборка виллы, смена постельного белья и полотенец раз в неделю.'],['Salted pool cleaned twice a week.','Piscine au sel nettoyée deux fois par semaine.','ทำความสะอาดสระน้ำเกลือสัปดาห์ละสองครั้ง','Бассейн с солёной водой чистится два раза в неделю.'],['Electricity','Électricité','ไฟฟ้า','Электричество'],['Extra','En supplément','มีค่าใช้จ่ายเพิ่มเติม','Дополнительно'],
['House rules','Règlement intérieur','กฎของบ้าน','Правила дома'],['Do not smoke inside the house.','Ne pas fumer à l’intérieur.','ห้ามสูบบุหรี่ภายในบ้าน','Не курить в доме.'],['Lost keys: 2,000 THB charge.','Clés perdues : frais de 2 000 THB.','กุญแจหาย: ค่าปรับ 2,000 บาท','Потеря ключей: штраф 2 000 бат.'],['Do not use illegal substances.','Ne pas consommer de substances illégales.','ห้ามใช้สารผิดกฎหมาย','Не употреблять запрещённые вещества.'],['Damaged bedsheets: 1,000 THB; towels: 500 THB.','Draps endommagés : 1 000 THB ; serviettes : 500 THB.','ผ้าปูที่นอนเสียหาย: 1,000 บาท; ผ้าเช็ดตัว: 500 บาท','Повреждённое бельё: 1 000 бат; полотенца: 500 бат.'],['No loud noise after 10 PM. Respect the neighborhood.','Pas de bruit après 22 h. Respectez le voisinage.','ห้ามส่งเสียงดังหลัง 22:00 น. โปรดเคารพเพื่อนบ้าน','Не шуметь после 22:00. Уважайте соседей.'],['No pets allowed.','Animaux interdits.','ไม่อนุญาตให้นำสัตว์เลี้ยงเข้าพัก','Домашние животные запрещены.'],['Do not throw anything in toilets. Blockage: 3,500 THB.','Ne rien jeter dans les toilettes. Débouchage : 3 500 THB.','ห้ามทิ้งสิ่งของลงในโถสุขภัณฑ์ ค่าท่ออุดตัน 3,500 บาท','Не бросать ничего в унитаз. Засор: 3 500 бат.'],['Excessive cleaning: 2,000 THB charge.','Nettoyage excessif : frais de 2 000 THB.','ค่าทำความสะอาดเพิ่มเติม 2,000 บาท','Чрезмерная уборка: 2 000 бат.'],['Lock all doors and windows when out and at night.','Verrouillez portes et fenêtres en votre absence et la nuit.','ล็อกประตูและหน้าต่างทุกบานเมื่อออกจากบ้านและในเวลากลางคืน','Запирайте все двери и окна при уходе и на ночь.'],
['Useful information','Informations utiles','ข้อมูลที่เป็นประโยชน์','Полезная информация'],['Emergency','Urgences','เหตุฉุกเฉิน','Экстренные службы'],['Tourist Police','Police touristique','ตำรวจท่องเที่ยว','Туристическая полиция'],['Ambulance / Medical','Ambulance / Urgences médicales','รถพยาบาล / การแพทย์','Скорая помощь'],['Getting around','Se déplacer','การเดินทาง','Транспорт'],['Rides','Trajets','บริการรถโดยสาร','Поездки'],['Ferries, buses & transfers','Ferries, bus et transferts','เรือเฟอร์รี่ รถบัส และรถรับส่ง','Паромы, автобусы и трансферы'],
['Our partner recommendations','Nos recommandations partenaires','คำแนะนำจากพาร์ทเนอร์','Рекомендации партнёров'],['Restaurants','Restaurants','ร้านอาหาร','Рестораны'],['Hand-picked tables and local flavours around Rawai.','Une sélection de bonnes tables et saveurs locales autour de Rawai.','ร้านอาหารคัดสรรและรสชาติท้องถิ่นรอบราไวย์','Избранные рестораны и местные вкусы Раваи.'],['Explore','Découvrir','สำรวจ','Подробнее'],['Spa, sauna & massages','Spa, sauna et massages','สปา ซาวน่า และนวด','Спа, сауна и массаж'],['Relax, recharge and enjoy a moment of pure well-being.','Détendez-vous et profitez d’un pur moment de bien-être.','ผ่อนคลาย เติมพลัง และเพลิดเพลินกับช่วงเวลาแห่งความสุข','Расслабьтесь и насладитесь моментом гармонии.'],['Bars & nightclubs','Bars et discothèques','บาร์และไนต์คลับ','Бары и ночные клубы'],['Sunset drinks, stylish venues and lively Phuket nights.','Verres au coucher du soleil, lieux élégants et nuits animées.','เครื่องดื่มยามพระอาทิตย์ตก สถานที่มีสไตล์ และค่ำคืนอันมีชีวิตชีวา','Напитки на закате, стильные места и яркие ночи Пхукета.'],['Motorbikes for rent','Location de motos','เช่ามอเตอร์ไซค์','Аренда мотобайков'],['Explore Rawai and Phuket freely, at your own pace.','Explorez Rawai et Phuket librement, à votre rythme.','สำรวจราไวย์และภูเก็ตได้อย่างอิสระตามจังหวะของคุณ','Исследуйте Раваи и Пхукет в своём темпе.'],
['Groceries stores','Supermarchés','ร้านขายของชำ','Продуктовые магазины'],['Gas stations','Stations-service','ปั๊มน้ำมัน','Автозаправки'],['Wine shop','Caviste','ร้านไวน์','Винный магазин'],['Selected address','Adresse sélectionnée','สถานที่แนะนำ','Рекомендуемый адрес'],['Breakfast / Lunch','Petit-déjeuner / Déjeuner','อาหารเช้า / อาหารกลางวัน','Завтрак / Обед'],['View on map','Voir sur la carte','ดูบนแผนที่','Посмотреть на карте'],
['Place all trash bags in the outdoor bins.','Placez tous les sacs-poubelle dans les conteneurs extérieurs.','นำถุงขยะทั้งหมดไปทิ้งในถังขยะด้านนอก','Положите все пакеты с мусором в уличные контейнеры.'],['Gather used towels and bedsheets in the living room.','Regroupez les serviettes et draps utilisés dans le salon.','รวบรวมผ้าเช็ดตัวและผ้าปูที่นอนที่ใช้แล้วไว้ในห้องนั่งเล่น','Соберите использованные полотенца и бельё в гостиной.'],['Wash dishes and leave them on the drying rack.','Lavez la vaisselle et laissez-la sur l’égouttoir.','ล้างจานและวางไว้บนชั้นตาก','Вымойте посуду и оставьте её на сушилке.'],['Thank you for your cooperation!','Merci pour votre coopération !','ขอบคุณสำหรับความร่วมมือ!','Спасибо за сотрудничество!'],['Villa information','Informations sur la villa','ข้อมูลวิลล่า','Информация о вилле'],['3 bedrooms Rawai','3 chambres à Rawai','3 ห้องนอน ราไวย์','3 спальни, Раваи'],['We wish you a wonderful stay!','Nous vous souhaitons un merveilleux séjour !','ขอให้คุณมีความสุขตลอดการเข้าพัก!','Желаем вам прекрасного отдыха!'],
['Discover our hand-picked restaurants around the villa','Découvrez notre sélection de restaurants autour de la villa','ค้นพบร้านอาหารที่เราคัดสรรรอบวิลล่า','Откройте нашу подборку ресторанов рядом с виллой'],['Swipe the logos to discover each place','Faites glisser les logos pour découvrir chaque adresse','ปัดโลโก้เพื่อดูแต่ละสถานที่','Листайте логотипы, чтобы открыть каждое место'],['Swipe to explore','Faites glisser pour explorer','ปัดเพื่อสำรวจ','Листайте для просмотра'],['WhatsApp','WhatsApp','WhatsApp','WhatsApp'],['Google Maps','Google Maps','Google Maps','Google Maps'],['Discover Rawai, Phuket','Découvrez Rawai, Phuket','ค้นพบราไวย์ ภูเก็ต','Откройте Раваи, Пхукет'],['Beaches, viewpoints, temples, seafood and island adventures.','Plages, points de vue, temples, fruits de mer et aventures insulaires.','ชายหาด จุดชมวิว วัด อาหารทะเล และการผจญภัยบนเกาะ','Пляжи, смотровые площадки, храмы, морепродукты и островные приключения.'],['Open video guide','Ouvrir le guide vidéo','เปิดวิดีโอแนะนำ','Открыть видеогид'],
['Clear sky','Ciel dégagé','ท้องฟ้าแจ่มใส','Ясно'],['Mainly clear','Généralement dégagé','ท้องฟ้าโปร่งเป็นส่วนใหญ่','Преимущественно ясно'],['Partly cloudy','Partiellement nuageux','มีเมฆบางส่วน','Переменная облачность'],['Overcast','Couvert','ท้องฟ้ามืดครึ้ม','Пасмурно'],['Fog','Brouillard','หมอก','Туман'],['Light drizzle','Bruine légère','ฝนปรอยเล็กน้อย','Лёгкая морось'],['Rain','Pluie','ฝนตก','Дождь'],['Thunderstorm','Orage','พายุฝนฟ้าคะนอง','Гроза'],['Weather temporarily unavailable','Météo temporairement indisponible','ไม่สามารถดูสภาพอากาศได้ชั่วคราว','Погода временно недоступна']
];
window.DG_TRANSLATION_ROWS.push(
['Seafood market and beachfront restaurants','Marché aux poissons et restaurants en bord de mer','ตลาดอาหารทะเลและร้านอาหารริมชายหาด','Рыбный рынок и рестораны на берегу моря'],
['French & Italian cuisine, steaks, pizza and seafood','Cuisine française et italienne, viandes, pizzas et fruits de mer','อาหารฝรั่งเศสและอิตาเลียน สเต๊ก พิซซ่า และอาหารทะเล','Французская и итальянская кухня, стейки, пицца и морепродукты'],
['French semi-gastronomic restaurant','Restaurant français semi-gastronomique','ร้านอาหารฝรั่งเศสกึ่งไฟน์ไดนิ่ง','Французский ресторан высокой кухни'],
['Gastro bar','Bar gastronomique','แกสโตรบาร์','Гастробар'],
['Italian restaurant','Restaurant italien','ร้านอาหารอิตาเลียน','Итальянский ресторан'],
['Healthy breakfast and lunch','Petit-déjeuner et déjeuner équilibrés','อาหารเช้าและอาหารกลางวันเพื่อสุขภาพ','Полезные завтраки и обеды'],
['Healthy food','Cuisine saine','อาหารเพื่อสุขภาพ','Здоровое питание'],
['Mexican restaurant','Restaurant mexicain','ร้านอาหารเม็กซิกัน','Мексиканский ресторан'],
['Wine shop with home delivery','Caviste avec livraison à domicile','ร้านไวน์พร้อมบริการจัดส่งถึงบ้าน','Винный магазин с доставкой на дом'],
['Spa, sauna, pool, massages, restaurant and bar','Spa, sauna, piscine, massages, restaurant et bar','สปา ซาวน่า สระว่ายน้ำ นวด ร้านอาหาร และบาร์','Спа, сауна, бассейн, массаж, ресторан и бар'],
['Massage at the shop or directly at the villa','Massage au salon ou directement à la villa','นวดที่ร้านหรือที่วิลล่า','Массаж в салоне или прямо на вилле'],
['CBD massage at home','Massage CBD à domicile','นวด CBD ถึงบ้าน','CBD-массаж на дому'],
['Bars and nightlife venue','Bars et lieu de vie nocturne','บาร์และสถานบันเทิงยามค่ำคืน','Бары и ночные развлечения'],
['Local bar','Bar local','บาร์ท้องถิ่น','Местный бар'],
['Nightclub and bars','Discothèque et bars','ไนต์คลับและบาร์','Ночной клуб и бары'],
['Scooter and motorbike rental','Location de scooters et motos','บริการเช่าสกู๊ตเตอร์และมอเตอร์ไซค์','Аренда скутеров и мотобайков'],
['Scooter rental','Location de scooters','บริการเช่าสกู๊ตเตอร์','Аренда скутеров'],
['Motorbike rental','Location de motos','บริการเช่ามอเตอร์ไซค์','Аренда мотобайков']
);
window.DG_TRANSLATIONS={en:{},fr:{},th:{},ru:{}};
window.DG_TRANSLATION_ROWS.forEach(row=>{window.DG_TRANSLATIONS.en[row[0]]=row[0];window.DG_TRANSLATIONS.fr[row[0]]=row[1];window.DG_TRANSLATIONS.th[row[0]]=row[2];window.DG_TRANSLATIONS.ru[row[0]]=row[3]});
window.DG_TRANSLATIONS.zh={
'Dream Garden Pool Villa — Guest Guide':'梦幻花园泳池别墅 — 入住指南',
'WELCOME TO':'欢迎来到',
'We are delighted to welcome you. We created this guide to help make your stay as enjoyable and comfortable as possible.':'很高兴欢迎您的到来。我们制作了这份指南，希望让您的住宿更加愉快舒适。',
'Villa address':'别墅地址','Scan location':'扫码查看位置','View on maps':'在地图上查看','Check-in & check-out':'入住与退房','Check-in':'入住','Check-out':'退房','From':'从','Before':'之前',
'Wi-Fi codes':'Wi-Fi 信息','Network':'网络','Password':'密码','Scan to connect':'扫码连接','Rawai weather':'拉威天气','Loading weather…':'正在加载天气…','Feels':'体感温度','Low / High':'最低 / 最高','Humidity':'湿度','Wind':'风速','Refresh Rawai weather':'刷新拉威天气',
'Places of interest':'周边景点','Sea Market':'海鲜市场','Dream Garden Pool Villa':'梦幻花园泳池别墅','Galerie photos':'照片画廊','Voir toutes les photos (20)':'查看全部照片（20）','Tout':'全部','Extérieur':'户外','Piscine':'泳池','Salon':'客厅','Cuisine':'厨房','Chambres':'卧室','Salles de bains':'浴室','Terrasse':'露台','Jardin':'花园','Aucune photo dans cette catégorie pour le moment.':'此分类目前没有照片。',
'Information about the villa':'别墅信息','3 bedrooms':'3 间卧室','3 bathrooms':'3 间浴室','Private pool — 12 × 5 m':'私人泳池 — 12 × 5 米','Maximum occupancy: 6 guests':'最多入住 6 位客人','Living room and fully equipped kitchen':'客厅和设施齐全的厨房','Covered parking for 2 cars':'可停放 2 辆车的有盖停车位','800 m² land · 250 m² villa':'占地 800 平方米 · 别墅面积 250 平方米',
'Included':'已包含','High-speed fiber Wi-Fi':'高速光纤 Wi-Fi','25L Water Dispenser':'25 升饮水机','Water':'用水','Laundry machine':'洗衣机','Barbecue gas':'烧烤燃气','Hair dryer':'吹风机','Pool towels':'泳池毛巾','Equipped kitchen':'设备齐全的厨房','Smart home system':'智能家居系统','Indoor & outdoor speakers':'室内外扬声器','100% LED lighting':'全 LED 照明','65" flat-screen TV & Box TV':'65 英寸平板电视和电视盒','Dishwasher':'洗碗机','Garden maintenance':'花园维护','Housekeeping':'客房清洁','Villa cleaning, bedsheets and towels changed once a week.':'每周清洁一次别墅，并更换床单和毛巾。','Salted pool cleaned twice a week.':'盐水泳池每周清洁两次。','Electricity':'电费','Extra':'额外收费',
'House rules':'房屋守则','Do not smoke inside the house.':'请勿在室内吸烟。','Lost keys: 2,000 THB charge.':'钥匙遗失：收取 2,000 泰铢。','Do not use illegal substances.':'禁止使用非法物品。','Damaged bedsheets: 1,000 THB; towels: 500 THB.':'床单损坏：1,000 泰铢；毛巾损坏：500 泰铢。','No loud noise after 10 PM. Respect the neighborhood.':'晚上 10 点后请勿喧哗，并尊重邻里。','No pets allowed.':'禁止携带宠物。','Do not throw anything in toilets. Blockage: 3,500 THB.':'请勿将任何物品投入马桶。堵塞处理费：3,500 泰铢。','Excessive cleaning: 2,000 THB charge.':'额外深度清洁费：2,000 泰铢。','Lock all doors and windows when out and at night.':'外出及夜间请锁好所有门窗。',
'Useful information':'实用信息','Emergency':'紧急情况','Tourist Police':'旅游警察','Ambulance / Medical':'救护车 / 医疗','Getting around':'出行服务','Rides':'叫车服务','Ferries, buses & transfers':'渡轮、巴士和接送服务',
'Our partner recommendations':'合作伙伴推荐','Restaurants':'餐厅','Hand-picked tables and local flavours around Rawai.':'精选拉威周边餐厅与当地风味。','Explore':'探索','Spa, sauna & massages':'水疗、桑拿和按摩','Relax, recharge and enjoy a moment of pure well-being.':'放松身心、恢复活力，享受纯粹的舒适时光。','Bars & nightclubs':'酒吧与夜店','Sunset drinks, stylish venues and lively Phuket nights.':'夕阳美酒、时尚场所与活力四射的普吉之夜。','Motorbikes for rent':'摩托车租赁','Explore Rawai and Phuket freely, at your own pace.':'按照自己的节奏，自由探索拉威和普吉。',
'Groceries stores':'杂货店','Gas stations':'加油站','Wine shop':'葡萄酒商店','Selected address':'精选商家','Breakfast / Lunch':'早餐 / 午餐','View on map':'在地图上查看','Place all trash bags in the outdoor bins.':'请将所有垃圾袋放入室外垃圾桶。','Gather used towels and bedsheets in the living room.':'请将使用过的毛巾和床单集中放在客厅。','Wash dishes and leave them on the drying rack.':'请清洗餐具并放在沥水架上。','Thank you for your cooperation!':'感谢您的配合！','Villa information':'别墅信息','3 bedrooms Rawai':'拉威三卧室别墅','We wish you a wonderful stay!':'祝您入住愉快！',
'Discover our hand-picked restaurants around the villa':'探索我们为您精选的别墅周边餐厅','Swipe the logos to discover each place':'滑动商标以查看各个地点','Swipe to explore':'滑动探索','WhatsApp':'WhatsApp','Google Maps':'谷歌地图','Discover Rawai, Phuket':'探索普吉拉威','Beaches, viewpoints, temples, seafood and island adventures.':'海滩、观景台、寺庙、海鲜与海岛探险。','Open video guide':'打开视频指南',
'Clear sky':'晴朗','Mainly clear':'大致晴朗','Partly cloudy':'局部多云','Overcast':'阴天','Fog':'有雾','Light drizzle':'小毛毛雨','Rain':'下雨','Thunderstorm':'雷雨','Weather temporarily unavailable':'天气暂时不可用',
'Seafood market and beachfront restaurants':'海鲜市场和海滨餐厅','French & Italian cuisine, steaks, pizza and seafood':'法式与意式料理、牛排、披萨和海鲜','French semi-gastronomic restaurant':'法式精致餐厅','Gastro bar':'美食酒吧','Italian restaurant':'意大利餐厅','Healthy breakfast and lunch':'健康早餐和午餐','Healthy food':'健康餐饮','Mexican restaurant':'墨西哥餐厅','Wine shop with home delivery':'提供送货上门的葡萄酒商店','Spa, sauna, pool, massages, restaurant and bar':'水疗、桑拿、泳池、按摩、餐厅和酒吧','Massage at the shop or directly at the villa':'可在按摩店或别墅内享受按摩','CBD massage at home':'上门 CBD 按摩','Bars and nightlife venue':'酒吧与夜生活场所','Local bar':'当地酒吧','Nightclub and bars':'夜店和酒吧','Scooter and motorbike rental':'踏板车和摩托车租赁','Scooter rental':'踏板车租赁','Motorbike rental':'摩托车租赁'
};
Object.assign(window.DG_TRANSLATIONS.en,{'Enlarge Google Maps QR code':'Enlarge Google Maps QR code','Enlarge Wi-Fi QR code':'Enlarge Wi-Fi QR code'});
Object.assign(window.DG_TRANSLATIONS.fr,{'Enlarge Google Maps QR code':'Agrandir le QR code Google Maps','Enlarge Wi-Fi QR code':'Agrandir le QR code Wi-Fi'});
Object.assign(window.DG_TRANSLATIONS.th,{'Enlarge Google Maps QR code':'ขยายคิวอาร์โค้ด Google Maps','Enlarge Wi-Fi QR code':'ขยายคิวอาร์โค้ด Wi-Fi'});
Object.assign(window.DG_TRANSLATIONS.ru,{'Enlarge Google Maps QR code':'Увеличить QR-код Google Maps','Enlarge Wi-Fi QR code':'Увеличить QR-код Wi-Fi'});
Object.assign(window.DG_TRANSLATIONS.zh,{'Enlarge Google Maps QR code':'放大谷歌地图二维码','Enlarge Wi-Fi QR code':'放大 Wi-Fi 二维码'});
Object.assign(window.DG_TRANSLATIONS.en,{'Galerie photos':'Photo gallery','Voir toutes les photos (20)':'View all photos (20)','Tout':'All','Extérieur':'Exterior','Piscine':'Pool','Salon':'Living room','Cuisine':'Kitchen','Chambres':'Bedrooms','Salles de bains':'Bathrooms','Terrasse':'Terrace','Jardin':'Garden','Aucune photo dans cette catégorie pour le moment.':'No photos are currently available in this category.'});
