const fs = require('fs');

const file = 'index.html';
let html = fs.readFileSync(file, 'utf8');
html = html.replace('class="mainpic" id="gallery"', 'class="mainpic"');

const gallery = `<section class="section gallery-section" id="gallery"><div class="wrap"><div class="gallery-heading"><div><div class="kicker">PALMS GARDEN —</div><h2 class="serif">La villa en images</h2></div><p>Découvrez la piscine, le jardin tropical et les espaces de vie de la villa.</p></div><div class="gallery-grid"><button class="gallery-item gallery-featured" type="button" aria-label="Agrandir la vue principale de la piscine"><img src="assets/images/gallery-elena/01-piscine-facade.png" alt="Piscine et façade tropicale d’Palms Garden Villa" loading="lazy"></button><button class="gallery-item" type="button" aria-label="Agrandir la piscine côté jardin"><img src="assets/images/gallery-elena/02-piscine-jardin.png" alt="Piscine privée bordée par le jardin tropical" loading="lazy"></button><button class="gallery-item" type="button" aria-label="Agrandir la vue large de la piscine"><img src="assets/images/gallery-elena/03-piscine-vue-large.png" alt="Vue large de la piscine et de la villa" loading="lazy"></button><button class="gallery-item" type="button" aria-label="Agrandir la terrasse avec transats"><img src="assets/images/gallery-elena/04-piscine-transats.png" alt="Terrasse ensoleillée avec transats au bord de la piscine" loading="lazy"></button><button class="gallery-item" type="button" aria-label="Agrandir la piscine avec palmier central"><img src="assets/images/gallery-elena/05-piscine-palmier.png" alt="Piscine avec palmier central et terrasse" loading="lazy"></button><button class="gallery-item" type="button" aria-label="Agrandir la terrasse près de la piscine"><img src="assets/images/gallery-elena/06-terrasse-piscine.png" alt="Terrasse et bain peu profond près de la piscine" loading="lazy"></button><button class="gallery-item gallery-wide" type="button" aria-label="Agrandir la terrasse ouverte sur le séjour"><img src="assets/images/gallery-elena/07-terrasse-sejour.png" alt="Terrasse ouverte sur le séjour et l’espace repas" loading="lazy"></button></div></div></section><div class="gallery-lightbox" id="galleryLightbox" aria-hidden="true"><button class="gallery-close" type="button" aria-label="Fermer la galerie">×</button><button class="gallery-nav gallery-prev" type="button" aria-label="Image précédente">‹</button><figure><img src="" alt=""><figcaption></figcaption></figure><button class="gallery-nav gallery-next" type="button" aria-label="Image suivante">›</button></div>\n`;

const marker = '<section class="section" id="rawai">';
if (!html.includes(marker)) throw new Error('Rawai insertion point not found');
if (!html.includes('gallery-section')) html = html.replace(marker, gallery + marker);
fs.writeFileSync(file, html);
