from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
path = ROOT / "index.html"
text = path.read_text(encoding="utf-8")

replacements = {
    '<html lang="fr">': '<html lang="en">',
    'aria-label="Afficher le site en plein écran"': 'aria-label="View the site in fullscreen"',
    '>EXPÉRIENCES<': '>EXPERIENCES<',
    '>GALERIE<': '>GALLERY<',
    'aria-label="Choisir la langue"': 'aria-label="Choose language"',
    'data-code="FR">FR · Français': 'data-code="EN">EN · English',
    'aria-label="Langues"': 'aria-label="Languages"',
    '<button class="is-active" data-language="fr" type="button" role="option" aria-selected="true">': '<button data-language="fr" type="button" role="option" aria-selected="false">',
    '<button data-language="en" type="button" role="option">': '<button class="is-active" data-language="en" type="button" role="option" aria-selected="true">',
    'BIENVENUE À RAWAI —': 'WELCOME TO RAWAI —',
    'LUXE, NATURE<br>& SÉRÉNITÉ<br><span>ABSOLUE</span>': 'LUXURY, NATURE<br>& ABSOLUTE<br><span>SERENITY</span>',
    "Votre villa privée d'exception à Phuket": 'Your exceptional private villa in Phuket',
    'Une expérience unique où chaque détail est pensé pour votre confort et faire de votre séjour un moment inoubliable.': 'A unique experience where every detail is designed for your comfort and an unforgettable stay.',
    'DÉCOUVRIR LA VILLA': 'DISCOVER THE VILLA',
    'Ouvrir l’adresse de la villa dans Google Maps': 'Open the villa address in Google Maps',
    'Adresse de la villa': 'Villa address',
    'Ouvrir la géolocalisation de la villa': 'Open the villa location',
    'QR code de géolocalisation de la villa': 'Villa location QR code',
    ' PERSONNES': ' GUESTS',
    " D'EXCEPTION": ' OF LUXURY',
    ' CHAMBRES': ' BEDROOMS',
    ' PISCINE PRIVÉE': ' PRIVATE POOL',
    'VOTRE VILLA PRIVÉE —': 'YOUR PRIVATE VILLA —',
    'Espace, luxe<br>et sérénité': 'Space, luxury<br>and serenity',
    "Nichée au cœur de Rawai, Palms Garden Villa offre un cadre idyllique pour des vacances inoubliables. Profitez d'espaces généreux, d'une décoration élégante et de services pensés pour votre confort.": 'Wake up to palm-framed pool views, unwind in the tropical garden and share long evenings beneath the spacious sala. Set on 800 m² of private grounds, Palms Garden Villa is designed for effortless stays in Rawai.',
    'VOIR LA GALERIE': 'VIEW THE GALLERY',
    '>CHAMBRES<': '>BEDROOMS<',
    '>SALLES DE BAINS<': '>BATHROOMS<',
    '>CUISINE<': '>KITCHEN<',
    '>PISCINE<': '>POOL<',
    '>PARKING COUVERT<': '>COVERED PARKING<',
    '>VOITURE + MOTO<': '>CAR + MOTORBIKE<',
    '>Informations utiles<': '>Useful information<',
    '⌂ Internet : Wi-Fi haut débit': '⌂ Internet: High-speed Wi-Fi',
    '⌂ Eau incluse': '⌂ Water included',
    '>Entretien<': '>Housekeeping<',
    '⌂ Nettoyage de la villa, draps et serviettes changés une fois par semaine.': '⌂ Villa cleaning, bedsheets and towels changed once a week.',
    '⌂ Piscine nettoyée deux fois par semaine.': '⌂ Pool cleaned twice a week.',
    '>Électricité <span>En supplément<': '>Electricity <span>Extra<',
    '>Équipements<': '>Amenities<',
    '✦ Piscine privée': '✦ Private pool',
    '✦ Baignoire': '✦ Bathtub',
    '✦ Cuisine équipée': '✦ Fully equipped kitchen',
    '✦ Barbecue (gaz)': '✦ Gas barbecue',
    '✦ Lit bébé disponible sur demande': '✦ Baby cot available upon request',
    '✦ Machine à laver': '✦ Washing machine',
    '✦ Serviettes & draps fournis': '✦ Towels & bedsheets provided',
    '✦ Sèche-cheveux': '✦ Hair dryer',
    '>Règles de la maison<': '>House rules<',
    "⊘ Interdiction de fumer à l'intérieur": '⊘ No smoking indoors',
    "⊘ Pas d'animaux": '⊘ No pets',
    '⊘ Respect du calme après 22h': '⊘ Keep noise down after 10 PM',
    "⊘ Pas de fêtes ou d'événements": '⊘ No parties or events',
    '⊘ Capacité max. 8 personnes': '⊘ Maximum capacity: 6 guests',
    '>Voir +<': '>View more<',
    ">En cas d'urgence<": '>In an emergency<',
    'Police touristique': 'Tourist Police',
    'Ambulance / Urgence': 'Ambulance / Emergency',
    '>La villa en images<': '>The villa in pictures<',
    'Agrandir la vue principale de la piscine': 'Enlarge the main pool view',
    'Piscine et façade tropicale d’Palms Garden Villa': 'Pool and tropical façade of Palms Garden Villa',
    'Agrandir la piscine côté jardin': 'Enlarge the garden-side pool',
    'Piscine privée bordée par le jardin tropical': 'Private pool bordered by the tropical garden',
    'Agrandir la cuisine et la salle à manger': 'Enlarge the kitchen and dining room',
    'Cuisine équipée et salle à manger d’Palms Garden Villa': 'Fully equipped kitchen and dining room at Palms Garden Villa',
    'Agrandir la première chambre': 'Enlarge the first bedroom',
    'Chambre élégante ouverte sur le jardin tropical': 'Elegant bedroom opening onto the tropical garden',
    'Agrandir la salle de bain': 'Enlarge the bathroom',
    'Salle de bain raffinée avec baignoire et double vasque': 'Refined bathroom with bathtub and double vanity',
    'Agrandir la terrasse près de la piscine': 'Enlarge the terrace by the pool',
    'Terrasse et bain peu profond près de la piscine': 'Terrace and shallow pool area',
    'Agrandir la chambre principale': 'Enlarge the master bedroom',
    'Chambre principale avec décoration contemporaine': 'Master bedroom with contemporary décor',
    'Télécharger cette image': 'Download this image',
    'Fermer la galerie': 'Close the gallery',
    'Image précédente': 'Previous image',
    'Image suivante': 'Next image',
    '>DÉCOUVREZ<': '>DISCOVER<',
    'Un village authentique entre mer cristalline, restaurants locaux, marchés et activités variées.': 'An authentic village with crystal-clear sea, local restaurants, markets and a variety of activities.',
    '>SERVICES SÉLECTIONNÉS<': '>SELECTED SERVICES<',
    '>Nos partenaires &amp; services<': '>Our partners &amp; services<',
    'Découvrir le district de Rawai': 'Discover the Rawai district',
    '>Supermarchés<': '>Supermarkets<',
    'Trouver le Makro le plus proche sur Google Maps': 'Find the nearest Makro on Google Maps',
    'Trouver le Lotus’s le plus proche sur Google Maps': 'Find the nearest Lotus’s on Google Maps',
    'Trouver le Tops Daily le plus proche sur Google Maps': 'Find the nearest Tops Daily on Google Maps',
    'Trouver le Big C le plus proche sur Google Maps': 'Find the nearest Big C on Google Maps',
    '>Stations-service<': '>Gas stations<',
    'Trouver la station PTT la plus proche sur Google Maps': 'Find the nearest PTT station on Google Maps',
    'Trouver la station Bangchak la plus proche sur Google Maps': 'Find the nearest Bangchak station on Google Maps',
    '>Applications utiles<': '>Useful apps<',
    '>Livraison de repas<': '>Food delivery<',
    '>Transport & billets<': '>Transport & tickets<',
    '>Disponible sur<': '>Available on<',
    'Disponible sur Google Play et l’App Store': 'Available on Google Play and the App Store',
    'Ouvrir Google Play dans un nouvel onglet': 'Open Google Play in a new tab',
    'Ouvrir l’App Store dans un nouvel onglet': 'Open the App Store in a new tab',
    '>Partagez votre expérience<': '>Share your experience<',
    '>Votre avis compte pour nous.<': '>Your review matters to us.<',
    'Google 5 étoiles': 'Google 5 stars',
    '>Laisser un commentaire →<': '>Leave a review →<',
    'aria-label="Fermer"': 'aria-label="Close"',
    'Nos adresses sélectionnées autour de la villa.': 'Our selected addresses around the villa.',
    'Clés perdues : frais de 2 000 THB.': 'Lost keys: 2,000 THB charge.',
    'Ne pas utiliser de substances illégales.': 'Do not use illegal substances.',
    'Draps endommagés : 1 000 THB ; serviettes : 500 THB.': 'Damaged bedsheets: 1,000 THB; towels: 500 THB.',
    'Ne rien jeter dans les toilettes. En cas de bouchage : 3 500 THB.': 'Do not throw anything in the toilets. Blockage charge: 3,500 THB.',
    'Nettoyage excessif : frais de 2 000 THB.': 'Excessive cleaning: 2,000 THB charge.',
    'Fermez toutes les portes et fenêtres lorsque vous sortez et pendant la nuit.': 'Lock all doors and windows when going out and at night.',
}

for source, target in replacements.items():
    if source not in text:
        raise RuntimeError(f"Expected source text not found: {source}")
    text = text.replace(source, target)

path.write_text(text, encoding="utf-8", newline="")
print(f"Applied {len(replacements)} English source replacements.")
